name: Analizar código Python

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Instalar mypy
        run: |
          pip install mypy
      - name: Analizar código
        run: |
          mypy *.py
      - name: Mostrar resultado
        run: |
          if [ $? -eq 0 ]; then
            echo "TODO OK"
          else
            echo "Error en el código"
          fi

# Analiza todos los archivos python de la raíz del proyecto en busca de errores
