name: Analizar código Python

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Analizar código Python
        run: |
          python -m py_compile *.py
          if [ $? -eq 0 ]; then
            echo "TODO OK"
          else
            echo "Error en el código"
          fi
