name: Analizar código Python

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint

      - name: Analyze code with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          if [ $? -eq 0 ]; then
            echo "TODO OK"
          else
            echo "Errores encontrados"
            exit 1
          fi

      - name: Analyze code with pylint
        run: |
          pylint *.py
          if [ $? -eq 0 ]; then
            echo "TODO OK"
          else
            echo "Errores encontrados"
            exit 1
          fi
