name: Añadir Topics a un Repositorio

on:
  workflow_dispatch:
    inputs:
      repo-url:
        description: 'URL del repositorio'
        required: true
        type: string
      topics:
        description: 'Lista de topics separados por comas'
        required: true
        type: string

jobs:
  add-topics:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar el repositorio y los topics
        run: |
          echo "Repositorio: ${{ github.event.inputs.repo-url }}"
          echo "Topics: ${{ github.event.inputs.topics }}"

