name: Añadir topics a un repositorio

on:
  workflow_dispatch:
    inputs:
      repository:
        description: Nombre del repositorio
        required: true
      topics:
        description: Topics a añadir (separados por comas)
        required: true

jobs:
  add-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Añadir topics al repositorio
        uses: actions/github-script@v6
        with:
          script: |
            curl -X PATCH \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/topics \
              -H 'Content-Type: application/json' \
              -d '{"names": ["${TOPICS}"]}'
        env:
          GITHUB_REPOSITORY: ${{ github.event.inputs.repository }}
          TOPICS: ${{ github.event.inputs.topics }}
