name: Add topics to repository
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Nombre del repositorio'
        required: true
      topics:
        description: 'Lista de topics separados por comas'
        required: true
jobs:
  add-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Add topics
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENDEACCESO }}
          REPOSITORY: ${{ github.event.inputs.repository }}
          TOPICS: ${{ github.event.inputs.topics }}
        run: |
          curl -X PATCH \
          https://api.github.com/repos/${REPOSITORIOGITHUB}/topics \
          -H 'Authorization: Bearer $GITHUB_TOKEN' \
          -H 'Content-Type: application/json' \
          -d '{"names": ["${TOPICS//,/\",\"}"]}'
