name: Agregar topics a un repositorio

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Nombre del repositorio'
        required: true
      topics:
        description: 'Topics a agregar (separados por comas)'
        required: true
      owner:
        description: 'Dueño del repositorio'
        required: true

jobs:
  agregar-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Agregar topics al repositorio
        run: |
          curl -X PATCH \
          https://api.github.com/repos/${owner}/${repository}/topics \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/vnd.github.mercy-preview+json' \
          -d '{"names": ["${topics}"]}'
        env:
          owner: ${{ github.event.inputs.owner }}
          repository: ${{ github.event.inputs.repository }}
          topics: ${{ github.event.inputs.topics }}
