name: Agregar topic a repositorio

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Nombre del repositorio'
        required: true
      topic-name:
        description: 'Nombre del topic'
        required: true

jobs:
  agregar-topic:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener ID del repositorio
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENDEACCESO }}
          REPO_NAME: ${{ github.event.inputs.repo-name }}
          TOPIC_NAME: ${{ github.event.inputs.topic-name }}
        run: |
          REPO_ID=$(curl -X GET \
          https://api.github.com/repos/${REPO_NAME} \
          -H 'Authorization: Bearer ${GITHUB_TOKEN}' \
          -H 'Content-Type: application/json' \
          | jq -r '.id')
          echo "REPO_ID=$REPO_ID" >> $GITHUB_ENV

      - name: Agregar topic al repositorio
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENDEACCESO }}
          REPO_ID: ${{ env.REPO_ID }}
          TOPIC_NAME: ${{ github.event.inputs.topic-name }}
        run: |
          curl -X PUT \
          https://api.github.com/repos/${REPO_ID}/topics \
          -H 'Authorization: Bearer ${GITHUB_TOKEN}' \
          -H 'Content-Type: application/json' \
          -d '{"names": ["${TOPIC_NAME}"]}'
