name: Add topics to repository
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Nombre del repositorio'
        required: true
      topics:
        description: 'Lista de topics separados por comas'
        required: true
jobs:
  add-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Add topics
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENDEACCESO }}
          REPOSITORY: ${{ github.event.inputs.repository }}
          TOPICS: ${{ github.event.inputs.topics }}
        run: |
          echo "Repositorio objetivo: $REPOSITORY"
          echo "Topics a aplicar: $TOPICS"
 
          curl -X PUT "https://api.github.com/repos/${REPOSITORY}/topics" \
          -H "Authorization: Bearer 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" \
          -H "Accept: application/vnd.github.mercy-preview+json" \
          -H "Content-Type: application/json" \
          -d "{\"names\": [\"${TOPICS//,/\",\"}\"]}"
