name: Agregar topics a un repositorio

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Nombre del repositorio'
        required: true
      topics:
        description: 'Topics a agregar (separados por comas)'
        required: true

jobs:
  agregar-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Agregar topics al repositorio
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.updateTopics({
              owner: github.context.repo.owner,
              repo: github.context.inputs.repo-name,
              names: github.context.inputs.topics.split(',')
            })
