name: Clonar y Copiar Repositorio

on:
  workflow_dispatch:

jobs:
  clonar-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clonar repositorio completo
        run: |
          git clone --mirror . repo-mirror

      - name: Comprimir repositorio
        run: |
          cd repo-mirror
          zip -r ../ClonadoRepositorio.zip .

      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: ClonadoRepositorio.zip
          path: ClonadoRepositorio.zip
