name: Clonar y Copiar Repositorio

on:
  workflow_dispatch:

jobs:
  clonar-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio completo
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git repo-mirror
          cd repo-mirror

      - name: Comprimir repositorio
        run: |
          cd ..
          zip -r ClonadoRepositorio.zip repo-mirror

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: ClonadoRepositorio.zip
          path: ClonadoRepositorio.zip
