name: AnalizarJavaPyhtonJavascript

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar herramientas de an치lisis
        run: |
          pip install pylint
          npm install eslint
          apt-get update && apt-get install -y default-jdk

      - name: Analizar c칩digo Python
        run: |
          pylint --errors-only $(find . -name "*.py")

      - name: Analizar c칩digo Java
        run: |
          javac $(find . -name "*.java")

      - name: Analizar c칩digo JavaScript
        run: |
          eslint --no-warn $(find . -name "*.js")
