name: AnalizarJavaPyhtonJavascript

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Instalar herramientas de an치lisis
        run: |
          pip install pylint
          npm install -g eslint
          sudo apt-get update && sudo apt-get install -y default-jdk

      - name: Analizar c칩digo Python
        run: |
          pylint $(find . -name "*.py")

      - name: Analizar c칩digo Java
        run: |
          javac $(find . -name "*.java")

      - name: Analizar c칩digo JavaScript
        run: |
          eslint $(find . -name "*.js")
