name: AnalizarJavaPyhtonJavascript

on:
  workflow_dispatch:

jobs:
  analizar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Instalar pylint
        run: |
          pip install pylint

      - name: Analizar código Python
        run: |
          pylint --recursive=yes --exit-zero $(find . -name "*.py")

      - name: Instalar javac
        run: |
          sudo apt-get update && sudo apt-get install -y default-jdk

      - name: Analizar código Java
        run: |
          javac $(find . -name "*.java")

      - name: Instalar eslint
        run: |
          npm install eslint

      - name: Analizar código JavaScript
        run: |
          eslint $(find . -name "*.js")
