name: Análisis de código

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repositorio a analizar'
        required: true
      token:
        description: 'Token de acceso al repositorio'
        required: true
      branch:
        description: 'Rama del repositorio a analizar'
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo }}
          token: ${{ github.event.inputs.token }}
          ref: ${{ github.event.inputs.branch }}

      - name: Análisis del código
        run: |
          # Aquí puedes agregar los comandos para analizar el código
          # Por ejemplo, puedes utilizar herramientas como eslint, sonarqube, etc.
          echo "Análisis del código en ${{ github.event.inputs.repo }}/${{ github.event.inputs.branch }}"
