name: Analisis + Copia a Nexus
on:
  push:
    branches:
      - nombredelarama
jobs:
  analizar-y-subir:
    runs-on: ubuntu-latest
    steps:
      - name: Analizar código
        uses: ./Pruebas/.github/workflows/AnalizarCodigo.yml
      - name: Subir backup a Nexus
        uses: ./Pruebas/.github/workflows/SubirBackupaNexus.yml
