on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repositorio a analizar'
        required: true
      branch:
        description: 'Rama del repositorio a analizar'
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo }}
          token: ${{ secrets.TokenDePruebas }}
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
          
      - name: Ejecutar código Python
        run: |
          find . -name "*.py" -exec python {} \;
