on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repositorio a analizar'
        required: true
      token:
        description: 'Token de acceso'
        required: true
      branch:
        description: 'Rama del repositorio a analizar'
        required: true
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo }}
          token: ${{ github.event.inputs.token }}
          ref: ${{ github.event.inputs.branch }}
      - name: Ejecutar código Python
        run: |
          find . -name "*.py" -exec python {} ;
