
name: Análisis de código

on:
  push:
    branches:
    ##### RAMAS DONDE SE EJECUTARÁ LA GH ACTION #####
      - main

jobs:
  analisis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        
      - name: Instalar dependencias
        run: |
          pip install pylint
          
      - name: Analizar código
        run: |
          pylint --output-format=text --output=report.txt .
      - name: Crear artefacto
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.txt
          
      - name: Enviar correo electrónico
        if: failure()
        env:
        ##### CAMBIAR 'Se ha detectado un error en el código' por el mensaje que quieres que salga en el correo #####
        ##### CAMBIAR CONTRASENA_CORREO por la contraseña real del correo de Remitente #####
          CORREO_REMITENTE: jefedeplanta@empresa.com
          CORREO_DESTINATARIO1: empleado1@empresa.com
          CORREO_DESTINATARIO2: empleado2@empresa.com
          CORREO_DESTINATARIO3: empleado3@empresa.com
          CONTRASENA_CORREO: TU_CONTRASEÑA_DE_CORREO
        run: |
          python -c "import smtplib; import email.mime.text; msg = email.mime.text.MIMEText('Se ha detectado un error en el código'); msg['Subject'] = 'Error en el código'; msg['From'] = 'jefedeplanta@empresa.com'; msg['To'] = 'empleado1@empresa.com, empleado2@empresa.com, empleado3@empresa.com'; server = smtplib.SMTP('smtp.gmail.com', 587); server.starttls(); server.login('jefedeplanta@empresa.com', 'TU_CONTRASEÑA_DE_CORREO'); server.sendmail('jefedeplanta@empresa.com', ['empleado1@empresa.com', 'empleado2@empresa.com', 'empleado3@empresa.com'], msg.as_string()); server.quit()"
