name: Instalar VS Code en Linux

on:
  push:
    branches:
      - main

jobs:
  install-vscode:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar VS Code
        run: |
          sudo snap install code --classic
          mkdir -p /home/runner/.config/Code
          sudo chown -R $USER:$USER /home/runner/.config/Code

      - name: Verificar instalación de VS Code
        run: |
          code --version
          node --version
