
name: Crear entornos
on: [push]
jobs:
  crear-entornos:
    runs-on: ubuntu-latest
    steps:
      - name: Crear entornos
        env:
          GITHUB_TOKEN: ${{ secrets.CALLAITO }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository }}
        run: |
          curl -X POST \
            https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/environments \
            -H 'Authorization: Bearer ${CALLAITO}' \
            -H 'Content-Type: application/json' \
            -d '{
              "name": "Desarrollo",
              "description": "Entorno de desarrollo"
            }'

          curl -X POST \
            https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/environments \
            -H 'Authorization: Bearer ${CALLAITO}' \
            -H 'Content-Type: application/json' \
            -d '{
              "name": "Preproducci贸n",
              "description": "Entorno de preproducci贸n"
            }'

          curl -X POST \
            https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/environments \
            -H 'Authorization: Bearer ${CALLAITO}' \
            -H 'Content-Type: application/json' \
            -d '{
              "name": "Producci贸n",
              "description": "Entorno de producci贸n"
            }'
