name: Obtener usuario y hora que ejecutó el push

on:
  push:
    branches:
      - main

jobs:
  obtener-usuario-y-hora:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener usuario y hora
        run: |
          echo "El usuario que ejecutó el push es: $GITHUB_ACTOR"
          echo "La hora en que se ejecutó el push es: $(date +'%Y-%m-%d %H:%M:%S')"
