on:
  workflow_dispatch:
    inputs:
################### CAMBIAR LOS VALUE POR LA INFORMACION CORRECTA ####################    
      jenkins_url: { value: 'bloqueado', description: 'URL del servidor de Jenkins' }
      jenkins_credentials: { value: 'usuarioJenkins:12345678', description: 'Credenciales de Jenkins' }
      proyecto_nombre: { value: 'Pruebas', description: 'Nombre del proyecto a migrar' }

jobs:
  migrar_proyecto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      - name: Instalar dependencias
        run: |
          pip install python-jenkins
      - name: Conectar con Jenkins
        env:
          JENKINS_URL: ${{ inputs.jenkins_url }}
          JENKINS_CREDENTIALS: ${{ inputs.jenkins_credentials }}
################### CAMBIAR LO QUE HAY DETRÁS DE TokenDePrueba por el nombre de tu Token ####################            
          GITHUB_TOKEN: ${{ secrets.TokenDePruebas }}
        run: |
          python -c "import jenkins; j = jenkins.Jenkins('$JENKINS_URL', username='usuarioJenkins', password='12345678'); print(j.get_job_info('Pruebas'))"
      - name: Descargar código del proyecto
        env:
          PROYECTO_NOMBRE: ${{ inputs.proyecto_nombre }}
          JENKINS_URL: ${{ inputs.jenkins_url }}
          JENKINS_CREDENTIALS: ${{ inputs.jenkins_credentials }}
        run: |
          python -c "import jenkins; j = jenkins.Jenkins('$JENKINS_URL', username='usuarioJenkins', password='12345678'); job_info = j.get_job_info('Pruebas'); print(job_info['lastSuccessfulBuild']['number'])"
