name: Mi Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2
      - name: Ejecuta mi acción
        uses: ./mi-action
        with:
          parametro1: 'valor1'
          parametro2: 'valor2'
