name: Subir Backup a Nexus
on:
  workflow_dispatch:
    inputs:
      servidor:
        description: Servidor de Nexus
        required: true
      usuario:
        description: Usuario del servidor
        required: true
      password:
        description: Contraseña del servidor
        required: true
      ruta:
        description: Ruta de destino en el servidor
        required: true
jobs:
  copiar-repositorio:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2
      - name: Crear copia del repositorio
        run: |
          mkdir copia
          cp -r . copia
      - name: Subir copia al servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ github.event.inputs.servidor }}
          username: ${{ github.event.inputs.usuario }}
          password: ${{ github.event.inputs.password }}
          script: |
            mkdir -p ${{ github.event.inputs.ruta }}
            cp -r /github/workspace/copia/* ${{ github.event.inputs.ruta }}/
