name: Subir Backup a Nexus
on:
  workflow_dispatch:
jobs:
  copiar-repositorio:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2
      - name: Crear copia del repositorio
        run: |
          mkdir copia
          cp -r . copia
      - name: Subir copia al servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVIDORNEXUS }}
          username: ${{ secrets.USUARIONEXUS }}
          password: ${{ secrets.PASSWORDUSUARIONEXUS }}
          script: |
            mkdir -p /ruta/de/destino/
            cp -r /github/workspace/copia/* /ruta/de/destino/
